name: Int-env-main
channels:
  - conda-forge
  - nvidia
  - oddt
  - pkgs/main
  - pyg
  - pytorch
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_kmp_llvm
  - absl-py=1.4.0=pyhd8ed1ab_0
  - aiohttp=3.8.4=py310h2372a71_1
  - aiosignal=1.3.1=pyhd8ed1ab_0
  - alabaster=0.7.16=py310h06a4308_0
  - async-timeout=4.0.2=pyhd8ed1ab_0
  - attrs=23.1.0=pyh71513ae_1
  - babel=2.11.0=py310h06a4308_0
  - biopython=1.79=py310h5764c6d_3
  - blas=1.0=mkl
  - blinker=1.6.2=pyhd8ed1ab_0
  - boltons=23.0.0=py310h06a4308_0
  - boost=1.82.0=h17c5347_3
  - boost-cpp=1.82.0=hdb19cb5_2
  - bottleneck=1.3.7=py310h0a54255_0
  - brotlipy=0.7.0=py310h7f8727e_1002
  - bzip2=1.0.8=h7b6447c_0
  - c-ares=1.19.1=hd590300_0
  - ca-certificates=2024.7.4=hbcca054_0
  - cachetools=5.3.1=pyhd8ed1ab_0
  - cairo=1.16.0=hb05425b_5
  - certifi=2024.7.4=py310h06a4308_0
  - cffi=1.15.1=py310h74dc2b5_0
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - click=8.1.3=unix_pyhd8ed1ab_2
  - conda=23.5.0=py310h06a4308_0
  - conda-package-handling=2.1.0=py310h06a4308_0
  - conda-package-streaming=0.8.0=py310h06a4308_0
  - cryptography=39.0.1=py310h9ce1e76_0
  - cuda-cudart=11.8.89=0
  - cuda-cupti=11.8.87=0
  - cuda-libraries=11.8.0=0
  - cuda-nvrtc=11.8.89=0
  - cuda-nvtx=11.8.86=0
  - cuda-runtime=11.8.0=0
  - cycler=0.11.0=pyhd8ed1ab_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - docker-pycreds=0.4.0=py_0
  - docutils=0.18.1=py310h06a4308_3
  - expat=2.5.0=hcb278e6_1
  - ffmpeg=4.3=hf484d3e_0
  - filelock=3.9.0=py310h06a4308_0
  - fontconfig=2.14.1=h4c34cd2_2
  - freetype=2.12.1=h267a509_2
  - freetype-py=2.3.0=pyhd8ed1ab_0
  - frozenlist=1.3.3=py310h5764c6d_0
  - fsspec=2023.6.0=pyh1a96a4e_0
  - giflib=5.2.1=h0b41bf4_3
  - gitdb=4.0.10=pyhd8ed1ab_0
  - gitpython=3.1.31=pyhd8ed1ab_0
  - glib=2.69.1=h4ff587b_1
  - gmp=6.2.1=h295c915_3
  - gmpy2=2.1.2=py310heeb90bb_0
  - gnutls=3.6.15=he1e5248_0
  - google-auth=2.21.0=pyh1a96a4e_0
  - google-auth-oauthlib=0.4.6=pyhd8ed1ab_0
  - greenlet=2.0.1=py310h6a678d5_0
  - grpcio=1.46.1=py310h44b9e0c_0
  - icu=73.2=h59595ed_0
  - idna=3.4=py310h06a4308_0
  - imageio=2.21.2=pyhfa7a67d_0
  - imagesize=1.4.1=py310h06a4308_0
  - importlib-metadata=6.7.0=pyha770c72_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - jbig=2.1=h7f98852_2003
  - jinja2=3.1.2=py310h06a4308_0
  - joblib=1.2.0=py310h06a4308_0
  - jpeg=9e=h0b41bf4_3
  - jsonpatch=1.32=pyhd3eb1b0_0
  - jsonpointer=2.1=pyhd3eb1b0_0
  - kiwisolver=1.4.4=py310h6a678d5_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libblas=3.9.0=12_linux64_mkl
  - libboost=1.82.0=h109eef0_2
  - libboost-headers=1.82.0=ha770c72_3
  - libboost-python=1.82.0=py310hcb52e73_3
  - libboost-python-devel=1.82.0=py310h17c5347_3
  - libcblas=3.9.0=12_linux64_mkl
  - libcublas=11.11.3.6=0
  - libcufft=10.9.0.58=0
  - libcufile=1.7.0.149=0
  - libcurand=10.3.3.53=0
  - libcusolver=11.4.1.48=0
  - libcusparse=11.7.5.86=0
  - libdeflate=1.8=h7f8727e_5
  - libexpat=2.5.0=hcb278e6_1
  - libffi=3.3=he6710b0_2
  - libgcc=15.2.0=h767d61c_7
  - libgcc-ng=15.2.0=h69a702a_7
  - libgfortran-ng=13.1.0=h69a702a_0
  - libgfortran5=13.1.0=h15d22d2_0
  - libiconv=1.17=h166bdaf_0
  - libidn2=2.3.4=h5eee18b_0
  - liblapack=3.9.0=12_linux64_mkl
  - liblzma=5.8.1=hb9d3cd8_2
  - liblzma-devel=5.8.1=hb9d3cd8_2
  - libnpp=11.8.0.86=0
  - libnvjpeg=11.9.0.86=0
  - libpng=1.6.39=h753d276_0
  - libprotobuf=3.20.1=h6239696_0
  - libstdcxx=15.2.0=h8f9b012_7
  - libstdcxx-ng=15.2.0=h4852527_7
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.3.0=h6f004c6_2
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp=1.2.4=h11a3e52_1
  - libwebp-base=1.2.4=h5eee18b_1
  - libxcb=1.15=h0b41bf4_0
  - libxml2=2.10.4=hfdd30dd_2
  - libzlib=1.2.13=hd590300_5
  - llvm-openmp=16.0.6=h4dfa4b3_0
  - lz4-c=1.9.3=h9c3ff4c_1
  - markdown=3.4.3=pyhd8ed1ab_0
  - markupsafe=2.1.1=py310h7f8727e_0
  - matplotlib-base=3.4.3=py310h23f4a51_2
  - matplotlib-inline=0.1.6=py310h06a4308_0
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py310h7f8727e_0
  - mkl_fft=1.3.1=py310hd6ae3a3_0
  - mkl_random=1.2.2=py310h00e6091_0
  - mpc=1.1.0=h10f8cd9_1
  - mpfr=4.0.2=hb69a4c5_1
  - multidict=6.0.4=py310h1fa729e_0
  - ncurses=6.4=h6a678d5_0
  - nettle=3.7.3=hbbd107a_1
  - networkx=2.8.4=py310h06a4308_1
  - numexpr=2.8.4=py310h8879344_0
  - numpy=1.26.4=py310hb13e2d6_0
  - numpydoc=1.7.0=py310h06a4308_0
  - oauthlib=3.2.2=pyhd8ed1ab_0
  - oddt=0.7=py_0
  - openbabel=3.1.1=py310h154a6b4_3
  - openh264=2.1.1=h4ff587b_0
  - openssl=1.1.1w=h7f8727e_0
  - packaging=23.0=py310h06a4308_0
  - pandas=1.5.3=py310h1128e8f_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pathtools=0.1.2=py_1
  - pcre=8.45=h9c3ff4c_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pillow=9.4.0=py310h6a678d5_0
  - pip=23.1.2=py310h06a4308_0
  - pixman=0.40.0=h36c2ea0_0
  - pluggy=1.0.0=py310h06a4308_1
  - promise=2.3=py310hff52083_7
  - prompt_toolkit=3.0.43=hd3eb1b0_0
  - protobuf=3.20.1=py310hd8f1fbe_0
  - psutil=5.9.5=py310h1fa729e_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - py3dmol=2.2.0=pyhd8ed1ab_0
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.7=py_0
  - pycairo=1.24.0=py310hda9f760_0
  - pycosat=0.6.4=py310h5eee18b_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pydeprecate=0.3.2=pyhd8ed1ab_0
  - pyg=2.3.1=py310_torch_2.0.0_cu118
  - pygments=2.15.1=py310h06a4308_1
  - pyjwt=2.7.0=pyhd8ed1ab_0
  - pyopenssl=23.0.0=py310h06a4308_0
  - pyparsing=3.1.0=pyhd8ed1ab_0
  - pysocks=1.7.1=py310h06a4308_0
  - python=3.10.4=h12debd9_0
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.10=2_cp310
  - pytorch=2.0.1=py3.10_cuda11.8_cudnn8.7.0_0
  - pytorch-cuda=11.8=h7e8668a_5
  - pytorch-lightning=1.7.4=pyhd8ed1ab_0
  - pytorch-mutex=1.0=cuda
  - pytorch-scatter=2.1.1=py310_torch_2.0.0_cu118
  - pytz=2023.3.post1=pyhd8ed1ab_0
  - pyu2f=0.1.5=pyhd8ed1ab_0
  - pyyaml=6.0=py310h5764c6d_5
  - rdkit=2023.03.3=py310hb79e901_1
  - readline=8.2=h5eee18b_0
  - reportlab=4.4.5=py310h7c4b9e2_0
  - requests=2.29.0=py310h06a4308_0
  - requests-oauthlib=1.3.1=pyhd8ed1ab_0
  - rlpycairo=0.4.0=pyh6c17108_0
  - rsa=4.9.1=pyhd8ed1ab_0
  - ruamel.yaml=0.17.21=py310h5eee18b_0
  - ruamel.yaml.clib=0.2.6=py310h5eee18b_1
  - scikit-learn=1.3.0=py310h1128e8f_0
  - scipy=1.7.3=py310hea5193d_0
  - seaborn=0.12.2=py310h06a4308_0
  - sentry-sdk=1.21.1=pyhd8ed1ab_0
  - setproctitle=1.3.2=py310h5764c6d_1
  - setuptools=67.8.0=py310h06a4308_0
  - shortuuid=1.0.11=pyhd8ed1ab_0
  - six=1.16.0=pyhd3eb1b0_1
  - smina=2020.12.10=hecca717_2
  - smmap=3.0.5=pyh44b312d_0
  - snowballstemmer=2.2.0=pyhd3eb1b0_0
  - sphinx=7.3.7=py310h5eee18b_0
  - sphinxcontrib-applehelp=1.0.2=pyhd3eb1b0_0
  - sphinxcontrib-devhelp=1.0.2=pyhd3eb1b0_0
  - sphinxcontrib-htmlhelp=2.0.0=pyhd3eb1b0_0
  - sphinxcontrib-jsmath=1.0.1=pyhd3eb1b0_0
  - sphinxcontrib-qthelp=1.0.3=pyhd3eb1b0_0
  - sphinxcontrib-serializinghtml=1.1.10=py310h06a4308_0
  - sqlalchemy=2.0.17=py310h2372a71_0
  - sqlite=3.41.2=h5eee18b_0
  - sympy=1.11.1=py310h06a4308_0
  - tabulate=0.9.0=py310h06a4308_0
  - tensorboard=2.11.2=pyhd8ed1ab_0
  - tensorboard-data-server=0.6.1=py310h597c629_4
  - tensorboard-plugin-wit=1.8.1=pyhd8ed1ab_0
  - threadpoolctl=2.2.0=pyh0d69192_0
  - tk=8.6.12=h1ccaba5_0
  - tomli=2.0.1=py310h06a4308_0
  - toolz=0.12.0=py310h06a4308_0
  - torchaudio=2.0.2=py310_cu118
  - torchmetrics=0.11.4=pyhd8ed1ab_0
  - torchtriton=2.0.0=py310
  - torchvision=0.15.2=py310_cu118
  - tornado=6.3.2=py310h2372a71_0
  - tqdm=4.65.0=py310h2f386ee_0
  - typing-extensions=4.7.1=hd8ed1ab_0
  - tzdata=2023c=h04d1e81_0
  - urllib3=1.26.16=py310h06a4308_0
  - wandb=0.13.1=pyhd8ed1ab_0
  - werkzeug=2.3.6=pyhd8ed1ab_0
  - wheel=0.38.4=py310h06a4308_0
  - xorg-libxau=1.0.11=hd590300_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xz=5.8.1=hbcc6ac9_2
  - xz-gpl-tools=5.8.1=hbcc6ac9_2
  - xz-tools=5.8.1=hb9d3cd8_2
  - yaml=0.2.5=h7f98852_2
  - yarl=1.9.2=py310h2372a71_0
  - zipp=3.15.0=pyhd8ed1ab_0
  - zlib=1.2.13=hd590300_5
  - zstandard=0.19.0=py310h5eee18b_0
  - zstd=1.5.2=h8a70e8d_1
  - pip:
    - Deprecated==1.2.18
    - Farama-Notifications==0.0.4
    - Flask==3.1.1
    - GitPython==3.1.44
    - Jinja2==3.1.6
    - QtPy==2.3.1
    - SQLAlchemy==2.0.41
    - Send2Trash==1.8.2
    - amqp==5.3.1
    - annotated-types==0.7.0
    - anyio==3.7.1
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - arrow==1.2.3
    - asttokens==2.2.1
    - backcall==0.2.0
    - beautifulsoup4==4.12.2
    - billiard==4.2.1
    - bleach==6.0.0
    - blinker==1.9.0
    - celery==5.5.2
    - charset-normalizer==3.4.2
    - click==8.2.1
    - click-didyoumean==0.3.1
    - click-plugins==1.1.1
    - click-repl==0.3.0
    - cloudpickle==3.1.1
    - comm==0.1.3
    - contourpy==1.3.2
    - cycler==0.12.1
    - databricks-sdk==0.54.0
    - debugpy==1.6.7
    - defusedxml==0.7.1
    - docker==7.1.0
    - docker-pycreds==0.4.0
    - exceptiongroup==1.1.2
    - executing==1.2.0
    - fastapi==0.115.12
    - fastjsonschema==2.17.1
    - flower==2.0.1
    - fonttools==4.58.0
    - fqdn==1.5.1
    - gitdb==4.0.12
    - graphene==3.4.3
    - graphql-core==3.2.6
    - graphql-relay==3.2.0
    - greenlet==3.2.2
    - gunicorn==23.0.0
    - gym==0.26.2
    - gym-notices==0.1.0
    - gymnasium==1.2.0
    - h11==0.16.0
    - humanize==4.12.3
    - ipykernel==6.24.0
    - ipython==8.14.0
    - ipython-genutils==0.2.0
    - ipywidgets==8.0.7
    - isoduration==20.11.0
    - itsdangerous==2.2.0
    - jedi==0.18.2
    - joblib==1.5.1
    - jsonschema==4.17.3
    - jupyter==1.0.0
    - jupyter-console==6.6.3
    - jupyter-events==0.6.3
    - jupyter_client==8.3.0
    - jupyter_core==5.3.1
    - jupyter_server==2.7.0
    - jupyter_server_terminals==0.4.4
    - jupyterlab-pygments==0.2.2
    - jupyterlab-widgets==3.0.8
    - kiwisolver==1.4.8
    - kombu==5.5.3
    - matplotlib==3.10.3
    - mistune==3.0.1
    - mlflow==2.22.0
    - mlflow-skinny==2.22.0
    - mpmath==1.2.1
    - nbclassic==1.0.0
    - nbclient==0.8.0
    - nbconvert==7.6.0
    - nbformat==5.9.0
    - nest-asyncio==1.5.6
    - notebook==6.5.4
    - notebook_shim==0.2.3
    - numpy==1.25.2
    - opentelemetry-api==1.33.1
    - opentelemetry-sdk==1.33.1
    - opentelemetry-semantic-conventions==0.54b1
    - overrides==7.3.1
    - packaging==24.2
    - pandas==2.2.3
    - pandocfilters==1.5.0
    - pip-chill==1.0.3
    - platformdirs==3.8.0
    - prometheus-client==0.17.0
    - prompt-toolkit==3.0.39
    - pyarrow==19.0.1
    - pydantic==2.11.5
    - pydantic_core==2.33.2
    - pyrsistent==0.19.3
    - python-dateutil==2.9.0.post0
    - python-json-logger==2.0.7
    - pyzmq==25.1.0
    - qtconsole==5.4.3
    - requests==2.32.3
    - rfc3339-validator==0.1.4
    - rfc3986-validator==0.1.1
    - scikit-learn==1.6.1
    - smmap==5.0.2
    - sniffio==1.3.0
    - soupsieve==2.4.1
    - sqlparse==0.5.3
    - stack-data==0.6.2
    - starlette==0.46.2
    - terminado==0.17.1
    - threadpoolctl==3.6.0
    - tinycss2==1.2.1
    - tornado==6.5.1
    - tqdm==4.67.1
    - traitlets==5.9.0
    - typing-inspection==0.4.1
    - typing_extensions==4.15.0
    - tzdata==2025.2
    - uri-template==1.3.0
    - uvicorn==0.34.2
    - vine==5.1.0
    - wcwidth==0.2.6
    - webcolors==1.13
    - webencodings==0.5.1
    - websocket-client==1.6.1
    - widgetsnbextension==4.0.8

prefix: "/home/etri3060/.local/share/mamba/envs/Int-env-main"
